#pragma once
#include <QtCore/qglobal.h>

#if defined(MEDIAN_FILTER_PLUGIN_LIBRARY)
#define MEDIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#define MEDIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif
